services:
  mongo:
    image: "mongo:6"
    container_name: "booking_devops_db"
    ports:
      - "27017:27017"

  backend:
    build: "./backend"
    container_name: "booking_devops_backend"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: 
      - "./backend/.env.prod"

  frontend:
    build: "./frontend"
    container_name: "booking_devops_frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - "./frontend/.env.prod"